Fix: Re-create browsers after killing all sessions on preboot
browserless/chrome pull request #3073
Opened 2023-03-09 00:09 UTC by andyMrtnzP

Fixes  https://github.com/browserless/chrome/issues/3030

2023-03-09 21:51 UTC, joelgriffith commented on src/chrome-helper.ts
> +  console.log(
Might want to `debug` or something here?

2023-03-09 21:55 UTC, joelgriffith commented on src/puppeteer-provider.ts
> -      if (this.config.prebootChrome && browser._prebooted) {
I'm pretty sure this is necessary... but it's not hitting me as to why

2023-03-09 22:07 UTC, joelgriffith commented
How about we just do this:

2023-03-13 20:17 UTC, andyMrtnzP commented
> In `route.ts`. Might still have to change the puppeteer-provider to clean out it's internal swarm cache of `chromeSwarm`. But might be a bit cleaner instead of passing instances around?

Yes, we ended up needing this change. And yes, it is way cleaner

2023-03-13 20:45 UTC, joelgriffith commented on src/chrome-helper.ts
> -  runningBrowsers = [];
This because `closeBrowser` takes care of removing them? Just wanted to double check

2023-03-13 21:06 UTC, joelgriffith commented on src/routes.ts
> +      puppeteerProvider.setSwarm(await puppeteerProvider.start());
Sorry for the churn on this one. Why don't we just make `puppeteerProvider.start` "reset" the `chromeSwarm` array anytime it's called? Maybe even rename it so it's more obvious that it's rotating the chrome instances it caches. Just trying to make it as idiomatic as possible.

2023-03-13 21:07 UTC, joelgriffith requested changes
One open question + a final thought. Thanks for seeing this one through

2023-03-14 04:02 UTC, joelgriffith commented
https://github.com/browserless/chrome/pull/3073/files#diff-7d02faf941f1b3ac4166544452aaafa8ebc68af58f356a84dec8d57c2af0a81eR80 is still manually pushing in chrome instances as they're created

2023-03-14 18:54 UTC, joelgriffith approved these changes

2023-03-14 18:55 UTC, merged